import AeolusUI

// Entry point for the Aeolus.app bundle target generated by XcodeGen.
//
// Everything the app actually does lives in the AeolusUI library, which `swift build`
// compiles on its own. That split is what lets CI type-check the entire user interface
// on a runner that cannot sign an app bundle, and it keeps this file to one line.
//
// Excluded from the AeolusUI SPM target: a library may not contain top-level code.
AeolusApp.main()
